name: Deploy to S3

on:
  push:
    branches:
      - master
    # tags:
    #   - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up .NET 7.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    # - name: Get the current tag
    #   id: get_tag
    #   run: |
    #     TAG_VERSION=$(git describe --tags)
    #     echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

    # - name: Update CSS version
    #   run: |
    #     sed -i 's@v=1@v='"$TAG_VERSION"'@' src/_includes/head.html

    - name: Retype Build
      uses: retypeapp/action-build@latest
      id: build
      with:
        strict: true
        license: "${{ secrets.RETYPE_LICENSE_KEY }}"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: |
        aws s3 sync ${{ steps.build.outputs.retype-output-path }} s3://solodev-cloud-documentation \
          --delete \
          --acl public-read \
          --cache-control "max-age=0,no-cache,no-store,must-revalidate"